resolver: nightly-2022-06-26
packages:
- .

extra-deps:
- canonical-json-0.6.0.0
- dom-lt-0.2.3
- int-cast-0.2.0.0
- lazy-search-0.1.2.1
- nothunks-0.1.3
- protolude-0.3.1

- git: https://github.com/Quid2/flat.git
  commit: 559617e058098b776b431e2a67346ad3adea2440
- git: https://github.com/input-output-hk/cardano-crypto.git
  commit: f73079303f663e028288f9f4a9e08bcca39a923e
  # nix-sha256: sha256-2Fipex/WjIRMrvx6F3hjJoAeMtFd2wGnZECT0kuIB9k=
- git: https://github.com/input-output-hk/cardano-base
  commit: 0f3a867493059e650cda69e20a5cbf1ace289a57
  subdirs:
    - base-deriving-via
    - binary
    - binary/test
    - cardano-crypto-class
    - cardano-crypto-praos
    - cardano-crypto-tests
    - measures
    - orphans-deriving-via
    - slotting
    - strict-containers
- git: https://github.com/mlabs-haskell/cardano-prelude
  commit: 713c7ae79a4d538fcd653c976a652913df1567b9
  subdirs:
    - cardano-prelude
    - cardano-prelude-test
  # nix-sha256: sha256-E+YSfUsvxdoOr7n7fz4xd7zb4z8XBRGNYOKipc2A1pw=
- git: https://github.com/input-output-hk/Win32-network
  commit: 3825d3abf75f83f406c1f7161883c438dac7277d
- git: https://github.com/input-output-hk/plutus
  commit: 3c81f60746f50b596d3209c38e048ebb473c93b8
  subdirs:
    - plutus-core
    - plutus-ledger-api
    - plutus-tx
    - plutus-tx-plugin
    - word-array
    - prettyprinter-configurable
    - stubs/plutus-ghc-stub
  # nix-sha256: sha256-SqZM0g/lPiJayXBAUkJweY8akmA/3M3vAVB+XHx/3WQ=
- git: https://github.com/haskell-effectful/effectful
  commit: f95b08cd3f33695c0ddef2db61f009a0c6a8e7aa
  subdirs:
  - effectful-core
  - effectful-th
  - effectful
- git: https://github.com/felixmulder/hedgehog-golden
  commit: 2686df225dc604c781c190346c514ef55df26ead

flags:
  cardano-prelude:
    development: true
  cardano-binary:
    development: true
  cardano-crypto-class:
    development: true
